# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoral',
            name='content',
        ),
        migrations.RemoveField(
            model_name='doctoral',
            name='title',
        ),
        migrations.AddField(
            model_name='doctoral',
            name='Doctor_Email_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='doctoral',
            name='Doctor_Name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='doctoral',
            name='Doctor_Password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='doctoral',
            name='Enter_Government_Registered_No',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
