# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20161011_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
