# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20161011_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Email_id',
            field=models.CharField(max_length=30),
        ),
    ]
