# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20161012_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoral',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Email_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Enter_Government_Registered_No',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
