# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20161012_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoral',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2016, 10, 12, 8, 50, 24, 176021, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Email_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Doctor_Password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='Enter_Government_Registered_No',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='updated',
            field=models.DateTimeField(max_length=200),
        ),
    ]
