# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20161012_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoral',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='doctoral',
            name='updated',
        ),
    ]
