# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_aadhar_no', models.CharField(default='', max_length=200, null=True)),
                ('diseases_or_symptoms', models.CharField(default='', max_length=200, null=True)),
                ('symptoms_description', models.TextField()),
                ('prescibed_medicines', models.CharField(default='', max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctoral',
            name='content',
        ),
        migrations.RemoveField(
            model_name='doctoral',
            name='title',
        ),
        migrations.AddField(
            model_name='doctoral',
            name='doctor_email_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctoral',
            name='doctor_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctoral',
            name='doctor_password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctoral',
            name='enter_government_registered_no',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctoral',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
