# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20161013_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_aadhar_no', models.CharField(max_length=13)),
                ('user_gender', models.CharField(max_length=1)),
                ('user_dob', models.DateTimeField()),
                ('user_address', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=10)),
            ],
        ),
    ]
